### PR TITLE
Refactor code for modularity, update gitignore

### PR DESCRIPTION
**Pull request by midopa**
Moved the hook handler code to their own app/package classes for better modularity.

Tested on Android 6.0/Cyanogenmod 13 with Miitomo 1.2.3.

### CODE REVIEW

**Comment by Nanolx** [comment]
In fact I planned something similar (but not as fancy) for the next version, seems you beat me to it.

**Comment by midopa** [comment]
Something just occurred to me. How does the Xposed framework know which class to load/call? Does it only call `XposedEntryPoint`? How does it know that? I'm afraid that it might be loading and calling all the classes in the `apps` package because it might be using reflection to load all classes that implement the `IXposedHookLoadPackage` interface. This is based on reading the [dev tutorial](https://github.com/rovo89/XposedBridge/wiki/Development-tutorial).

If this is true, then I need to redo this. Simplest solution would be to have a separate internal interface that does the same thing, but is named differently so Xposed won't invoke it. Thoughts?

**Comment by midopa** [comment]
Looking at the code, it might not be a huge bug, since each of the 'apps'  are using package-unique class names for their hooks. Still, if Xposed loads by just looking for implementing classes, then I still think this should be fixed.

**Comment by Nanolx** [comment]
have a look at the file app/src/main/assets/xposed_init this file defines the entry point for Xposed, since we only list
- org.nanolx.securitybypasser.XposedEntryPoint

in it, Xposed should only use this one, see [dev tutorial#assets/xposed_init](https://github.com/rovo89/XposedBridge/wiki/Development-tutorial#assetsxposed_init)

**Comment by midopa** [comment]
Oh, OK. No problem then!

**Pull request merged**
